// app/layout.tsx
import "./globals.css";
import { DM_Sans, DM_Serif_Display } from "next/font/google";
import type { Metadata } from "next";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";
import { ThemeProvider } from "./components/ThemeProvider";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-dm-sans",
});
const dmSerif = DM_Serif_Display({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-dm-serif-display",
});

export const metadata: Metadata = {
  title: "Kings Web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body
        className={`${dmSans.variable} ${dmSerif.variable} antialiased`}
      >
        {/* ThemeProvider must wrap all client-side theming */}
        <ThemeProvider
          attribute="class"               // toggles 'class="light"' / 'class="dark"'
          defaultTheme="system"           // or 'light' | 'dark'
          enableSystem                     // respect OS preference
          disableTransitionOnChange        // avoid flash on theme switch
        >
          <NavBar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}